In [3]:
import torch
acts = torch.randn((6, 2)) * 2
acts

tensor([[ 3.3160,  0.3095],
        [ 0.2496,  3.8757],
        [ 2.8256, -0.3437],
        [-1.1270,  0.2464],
        [-2.4359,  1.6934],
        [ 0.2760,  0.0347]])

In [4]:
acts.sigmoid()

tensor([[0.9650, 0.5768],
        [0.5621, 0.9797],
        [0.9440, 0.4149],
        [0.2447, 0.5613],
        [0.0805, 0.8447],
        [0.5686, 0.5087]])

In [7]:
torch.softmax(acts, dim=1)

tensor([[0.9529, 0.0471],
        [0.0259, 0.9741],
        [0.9597, 0.0403],
        [0.2021, 0.7979],
        [0.0158, 0.9842],
        [0.5600, 0.4400]])